erpnext_task:
  description: >
    User asked: {topic}. Search the ERPNext database using your tools and provide an answer.
  expected_output: >
    Clear, human-readable answer based on ERPNext data about {topic}.
  agent: erpnext_agent  
