erpnext_task:
  description: >
    The user has asked: "{topic}". Query the ERPNext database to get an accurate, factual answer. Use SQL-like logic, not speculation.
  expected_output: >
    Return a simple, human-readable answer from the ERPNext database. Do not summarize or interpret — just state the answer.
  agent: erpnext_agent
